// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuz5RMsWOP8CHKY6zBzQ3ZI-d7HI_xMnc',
    appId: '1:350463720958:web:a5e7795229554eb2c7d4af',
    messagingSenderId: '350463720958',
    projectId: 'meddidoc',
    authDomain: 'meddidoc.firebaseapp.com',
    databaseURL: 'https://meddidoc-default-rtdb.firebaseio.com',
    storageBucket: 'meddidoc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIZ8NbIK0zKZvF6-TUvdbSLhHeCAkYpsU',
    appId: '1:350463720958:android:93b3813bf0d487adc7d4af',
    messagingSenderId: '350463720958',
    projectId: 'meddidoc',
    databaseURL: 'https://meddidoc-default-rtdb.firebaseio.com',
    storageBucket: 'meddidoc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDeCwLzSP7j5C1SvhrJbT5KsS8y5pujJ8',
    appId: '1:350463720958:ios:af0088c1403e5026c7d4af',
    messagingSenderId: '350463720958',
    projectId: 'meddidoc',
    databaseURL: 'https://meddidoc-default-rtdb.firebaseio.com',
    storageBucket: 'meddidoc.appspot.com',
    iosBundleId: 'com.example.medidocDoctor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDeCwLzSP7j5C1SvhrJbT5KsS8y5pujJ8',
    appId: '1:350463720958:ios:af0088c1403e5026c7d4af',
    messagingSenderId: '350463720958',
    projectId: 'meddidoc',
    databaseURL: 'https://meddidoc-default-rtdb.firebaseio.com',
    storageBucket: 'meddidoc.appspot.com',
    iosBundleId: 'com.example.medidocDoctor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuz5RMsWOP8CHKY6zBzQ3ZI-d7HI_xMnc',
    appId: '1:350463720958:web:9459d0d825aedf88c7d4af',
    messagingSenderId: '350463720958',
    projectId: 'meddidoc',
    authDomain: 'meddidoc.firebaseapp.com',
    databaseURL: 'https://meddidoc-default-rtdb.firebaseio.com',
    storageBucket: 'meddidoc.appspot.com',
  );
}
